name: Build & Publish Toolchain

on: [push, pull_request]
jobs:   
  toolchain:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: echo cwd; echo $PATH
    - name: build
      run: make sdk
    - uses: actions/upload-artifact@v2
      with:
        name: miyoo-toolchain
        path: output/images/arm-buildroot-linux-musleabi_sdk-buildroot.tar.gz
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
  docker:
    needs: toolchain
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    runs-on: ubuntu-20.04
    env:
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
      DOCKERHUB_USERNAME: miyoocfw
    steps:
    - uses: actions/checkout@v3

    # download and extract the artefact
    - uses: actions/download-artifact@v3
      with: 
        name: miyoo-toolchain
    - run: tar -xvf arm-buildroot-linux-musleabi_sdk-buildroot.tar.gz

    - name: Log into docker hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        # create token at https://hub.docker.com/settings/security
        # token needs to have read, write, and delete permissions - read and write only leads to a login error (wtf?)
        # set value at https://github.com/MiyooCFW/toolchain/settings/secrets/actions
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    # todo: consider also publishing to github's container registry
